### ISSUE TITLE
yarn后启动不了

### ISSUE THREAD

**Issue by wjjhhh** [JasKang/elenext#14]
![image](https://user-images.githubusercontent.com/19969184/104087140-88e2be80-5298-11eb-9fb5-dbc65bdead1f.png)
yarn之后，yarn start报错

**Comment by JasKang** [comment]
先 yarn dev 或 yarn build
再 yarn start

**Comment by wjjhhh** [comment]
> 先 yarn dev 或 yarn build
> 再 yarn start

是根目录吗--
![image](https://user-images.githubusercontent.com/19969184/104093049-fe638480-52c2-11eb-9593-8294e987b5db.png)
![Uploading image.png…]()

**Comment by JasKang** [comment]
根目录，你可以删掉 .yarnrc 文件试下

**Comment by JasKang** [comment]
fiexd #
